// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModeKind } from "../ModeKind";
import type { PlanModePhase } from "../PlanModePhase";
import type { CollaborationModeSettings } from "./CollaborationModeSettings";

/**
 * EXPERIMENTAL - collaboration mode override for turn/start.
 */
export type CollaborationMode = { mode: ModeKind, planPhase: PlanModePhase | null, settings: CollaborationModeSettings, };
