// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "../ReasoningEffort";

/**
 * EXPERIMENTAL - collaboration mode settings for turn/start.
 */
export type CollaborationModeSettings = { model: string, reasoningEffort: ReasoningEffort | null, developerInstructions: string | null, };
