// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillInvocationType } from "./SkillInvocationType";

export type SkillUsedNotification = { threadId: string, turnId: string, name: string, invocationType: SkillInvocationType, };
