// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnPlanStepStatus } from "./TurnPlanStepStatus";

export type ThreadActivePlanRow = { id: string, step: string, status: TurnPlanStepStatus, path: string, details: string, inputs: Array<string>, outputs: Array<string>, dependsOn: Array<string>, acceptance: string | null, };
