// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnPlanStepStatus } from "./TurnPlanStepStatus";

export type TurnPlanStep = { id: string | null, step: string, status: TurnPlanStepStatus, path: string | null, details: string | null, inputs: Array<string> | null, outputs: Array<string> | null, dependsOn: Array<string> | null, acceptance: string | null, };
